### ISSUE TITLE
State Monitoring

### ISSUE THREAD

**Issue by mbfm** [eclipse-opendut/opendut#199]
We want to monitor the state of each peer and as such the cluster that they're contained in.

Tasks:
* Determine PeerState
  * [x] Determine PeerConfiguration apply state
  * [x] #386
  * Reporting from Leader (can be potentially done later)
    * [ ] #329
    * [ ] #324
* [ ] #419
* [ ] #391
* [ ] #392
* [ ] #387
* [ ] #12
* [ ] #420

* [ ] Show ClusterState in LEA
  * [ ] ClusterManager offers API for requesting simplified ClusterState (ready, failed, undeployed etc.)
  * [x] #315
  * [ ] LEA shows state in health traffic light
* [ ] Show detailed PeerState in LEA
  * [ ] PeerManager offers API for requesting simplified PeerState (`PeerHealth`)
  * [ ] LEA shows state in health traffic light
  * [ ] LEA shows errors, if any
  * [ ] PeerManager offers API for requesting detailed PeerState (`PeerConfigurationStatusReport`)
  * [ ] LEA shows progress for peer configuration apply (which tasks have been realized)

Description of the intended architecture: https://opendut.eclipse.dev/book/architecture/carl/peer/configuration-state-loop.html
